### ISSUE TITLE
[question] pacman licensing

### ISSUE THREAD

**Issue by petrklus** [platzhersh/pacman-canvas#1]
Hi,

First of all, great job on the development!

I was curious what was the licensing of the code - is it GPL/BSD/MIT or anything similar?

**Comment by relrod** [comment]
@platzhersh is there any way you would reconsider this? The Creative Commons folks themselves [advise against using CC for software projects] (https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software).

> Can I apply a Creative Commons license to software?
> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available.

Might I suggest MIT or BSD instead?
