### ISSUE TITLE
Highscores

### ISSUE THREAD

**Issue by JasonWStanley** [platzhersh/pacman-canvas#12]
I'd love to get the highscore functionality working, Is there a working example of this at all?

**Comment by platzhersh** [comment]
What exactly do you refer to?

**Comment by JasonWStanley** [comment]
Basically when I enter my name after the game is over it doesn't record my score or name. I've uploaded all the files to a webserver to test.

**Comment by platzhersh** [comment]
Do you see any errors in the web dev console?

**Comment by JasonWStanley** [comment]
I get this: HTML1512: Unmatched end tag.

And this: jquery-1.10.2.min.js:6 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience.

**Comment by platzhersh** [comment]
Note that there is the method resetHighscore() in the db-handler.php file. This should setup the sqlite database, including the db schema.

You can trigger it by making a POST request to http://your-server/data/db-handler.php and the parameter action=reset.
Check if the pacman.db file gets properly created in the data folder.

**Comment by JasonWStanley** [comment]
There is a pacman.db file created and it detects that I've entered names.

**Comment by platzhersh** [comment]
Check the comment on line 3: https://github.com/platzhersh/pacman-canvas/blob/master/data/db-handler.php#L3
you have to adapt the $hostdomain variable

**Comment by JasonWStanley** [comment]
Yep I've spotted that. I've setup a temporary site to test this, the location is https://svm-game.000webhostapp.com/ so the $hostdomain variable would be the same thing right?

**Comment by JasonWStanley** [comment]
This is what's showing up on the pacman.db file - https://snag.gy/cwbOy8.jpg

**Comment by platzhersh** [comment]
You're entries are all marked as cheaters. I had a bug in my code, that wasn't covering https for domain checks. I just added that. Can you try with the latest version of db-handler?

**Comment by JasonWStanley** [comment]
Yes! Thank you so much for the help, that was it!

**Comment by platzhersh** [comment]
Awesome! Glad I was able to help! And thanks for helping me improve the code.

Hope you enjoy the game 👍
