### ISSUE TITLE
Replacing Pac-Man with an image

### ISSUE THREAD

**Issue by JasonWStanley** [platzhersh/pacman-canvas#13]
Is it possible to replace the Pac-Man shape with an image using **_context.drawImage_**?

**Comment by platzhersh** [comment]
Hi Jason,

of course you can. This is code. everything is possible ;)
Pacman gets drawn every time the renderContent() method is called.
The code to draw him is here:
https://github.com/platzhersh/pacman-canvas/blob/master/pacman-canvas.js#L1434

You can easily replace this by whatever you want.

The code could also be moved to a draw() function on the pacman object actually.

**Comment by JasonWStanley** [comment]
Thanks,

I thought it was possible but I can't seem to find the correct code to insert an image without it messing up the existing code.

**Comment by platzhersh** [comment]
You can check the draw function of the ghosts: https://github.com/platzhersh/pacman-canvas/blob/master/pacman-canvas.js#L639

**Comment by JasonWStanley** [comment]
Apologies, I don't mean to bother you. I've tried a draw function but the image doesn't load onto the canvas. https://snag.gy/tRXbg5.jpg

**Comment by platzhersh** [comment]
You should use `image.src` if you instantiate the Image with that name.

The variable `gamecharacter` has never been defined.

**Comment by JasonWStanley** [comment]
Thanks, I've changed that to `image.src` and referenced it in the `context.drawimage` but it's still not produced anything.

**Comment by platzhersh** [comment]
context.drawImage(this.image, pacman.posX, pacman.posY, 2*pacman.radius, 2*pacman.radius);

No need to use angle at all.

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage

**Comment by platzhersh** [comment]
Well, its SVG. So it should adapt. I think I can't help you any further :)
Try compare to the draw function of the ghost object, like mentioned above. And check if there are differences. Also if you see errors in the browser console.

**Comment by JasonWStanley** [comment]
Okay thank you for your help, I apologise for bothering you.

**Comment by platzhersh** [comment]
No worries :) Wish you good luck!

**Comment by zorromustafa** [comment]
still not working can someone help me with a solution
