### ISSUE TITLE
map.json blocked by CORS policy

### ISSUE THREAD

**Issue by Frank-Einstein** [platzhersh/pacman-canvas#14]
When I unzip it and open index.html directly with Chrome, the page is loading but the game is not working and this is what I can see in the console:

"Access to XMLHttpRequest at 'file:///D:/SRC/HTML5-EXAMPLES/pacman-canvas-master/data/map.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https..."

I don't know about other browsers but, is there any file I can edit to fix this problem with Google Chrome?

**Comment by noamvaza** [comment]
Use this
https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en

Do not other the file directly.

**Comment by Frank-Einstein** [comment]
Thank you for your response, I was just curious if there was a quick trick that could be used to view/edit the game without using a web-server. I guess my only other option would be to use some kind of Chrome Anti-CORS-Filter addon... Or copy the content of map.json inside index.html ?

**Comment by platzhersh** [comment]
@Frank-Einstein 

you will always have these CORS issues with XHRequests when you're not running on a webserver, so this is a general thing.

I'll therefor close this issue.
