### ISSUE TITLE
Get level map causes:  XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience

### ISSUE THREAD

**Issue by C0kkie** [platzhersh/pacman-canvas#15]
// get Level Map
			$.ajax({
				url: mapConfig,
				async: false,
				 beforeSend: function(xhr){
					if (xhr.overrideMimeType) xhr.overrideMimeType("application/json"); 
				},
				dataType: "json",
				success: function (data) {
					game.map =  data;
				}
			});

as far as i am aware, async false isnt allowed anymore and causes a error in the console

**Comment by platzhersh** [comment]
@C0kkie thank you. 

You are more than welcome to create a pull request to fix this if you like.

Otherwise I'll see when I have time myself to fix it.

**Comment by C0kkie** [comment]
Sadly i dont have really time too, also i dont really see the reason why there is async false
