### ISSUE TITLE
It doesn't work on Chrome

### ISSUE THREAD

**Issue by orzzzl** [platzhersh/pacman-canvas#3]
I have tried that it works perfectly on the Safari, but it doesn't work on chrome.
I don't know if anyone has the same issue with me.

**Comment by mrngoitall** [comment]
Chrome blocks the request to `data/map.json` if you try opening this project by just double-clicking on the index.htm file. If you're on a Mac/Linux machine, try running `python -m SimpleHTTPServer 8000` in the project root directory and direct Chrome to http://127.0.0.1:8000/

**Comment by platzhersh** [comment]
thx @mrngoitall for responding
