### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by r3duc3** [platzhersh/pacman-canvas#31]
**SQL Injection vulnerability**
<https://github.com/platzhersh/pacman-canvas/blob/master/data/db-handler.php#L99>

write up: <https://archive.org/details/sql-injection-pacman.platzh1rsch.ch>

**Comment by platzhersh** [comment]
Fixed: https://github.com/platzhersh/pacman-canvas/commit/29522c90ca1cebfce6453a5af5a45281d99b0646
