### ISSUE TITLE
Cannot get maze canvas on any browser

### ISSUE THREAD

**Issue by ngagecompany** [platzhersh/pacman-canvas#4]
I have loaded the code to http://tngctest.com/ecoman , and the maze and graphics do not show up after clicking 'Click to Play'. (see screen shot)
![screen shot 2015-08-11 at 5 26 27 pm](https://cloud.githubusercontent.com/assets/9770567/9211188/73f380e8-404e-11e5-8c80-7d2aedacf069.png)

I think this may have something to do with the fact that the game cannot load the Highscores. Could this be related to the map.json or manifest.json and verification key?

**Comment by noamvaza** [comment]
The map file is missing...
404 http://tngctest.com/ecoman/data/map.json

**Comment by ngagecompany** [comment]
I see that, but there seems to be a problem, as I get the same thing when I
upload locally. the screen shot below is from when I clicked on the
index.htm file on my local folder, and it still doesn't load the map...and
the map.json file is there.

On Wed, Aug 12, 2015 at 3:43 AM, noamvaza <notifications@github.com> wrote:

> The map file is missing...
> 404 http://tngctest.com/ecoman/data/map.json
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/platzhersh/pacman-canvas/issues/4#issuecomment-130204131>
> .
>



-- 
Gregory Panos
CEO/Founder
The nGage Company, Inc.
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg2B89V8W2zqjvv4WYsTFVQBb2Y56dHtmf7qQxPR02?t=http%3A%2F%2Fngagecompany.com%2F&si=6216724911226880&pi=e517ac5a-5b57-4bf0-e36d-a4bd0251e081>
greg@ngagecompany.com <gp@thengagecompany.com>
484.685.0565 Office
484.354.6615 Cell

**Comment by platzhersh** [comment]
If you want to run the game locally, you need to have a webserver running. If you just click the index.htm file, Javascript is blocked from asynchronously loading ressources into the DOM. Google Cross Origin Request for more information.

**Comment by ngagecompany** [comment]
The file map.json is on my server, yet it does not show up when you put the
address in the browser. Is it hidden for some reason?




​

On Wed, Aug 12, 2015 at 7:16 AM, platzhersh <notifications@github.com>
wrote:

> If you want to run the game locally, you need to have a webserver running.
> If you just click the index.htm file, Javascript is blocked from
> asynchronously loading ressources into the DOM. Google Cross Origin Request
> for more information.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/platzhersh/pacman-canvas/issues/4#issuecomment-130263753>
> .
>



-- 
Gregory Panos
CEO/Founder
The nGage Company, Inc.
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg2B89V8W2zqjvv4WYsTFVQBb2Y56dHtmf7qQxPR02?t=http%3A%2F%2Fngagecompany.com%2F&si=6216724911226880&pi=21326ca1-42fd-46fc-d833-5cbfcde9a9f1>
greg@ngagecompany.com <gp@thengagecompany.com>
484.685.0565 Office
484.354.6615 Cell

**Comment by noamvaza** [comment]
Maybe you should check your .htaccess file or permissions.

**Comment by platzhersh** [comment]
@ngagecompany This definitely has something to do with your webserver settings. Check if your webhoster allows direct access to .json files.

**Comment by ngagecompany** [comment]
Thanks will do that


On Wed, Aug 12, 2015 at 7:58 AM, platzhersh <notifications@github.com>
wrote:

> @ngagecompany <https://github.com/ngagecompany> This definitely has
> something to do with your webserver settings. Check if your webhoster
> allows direct access to .json files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/platzhersh/pacman-canvas/issues/4#issuecomment-130272423>
> .
>



-- 
Gregory Panos
CEO/Founder
The nGage Company, Inc.
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg2B89V8W2zqjvv4WYsTFVQBb2Y56dHtmf7qQxPR02?t=http%3A%2F%2Fngagecompany.com%2F&si=6216724911226880&pi=14215f6b-a731-4050-987f-389085df10e2>
greg@ngagecompany.com <gp@thengagecompany.com>
484.685.0565 Office
484.354.6615 Cell

**Comment by ngagecompany** [comment]
That fixed it. Thanks!


On Wed, Aug 12, 2015 at 8:02 AM, Gregory Panos <gp@thengagecompany.com>
wrote:

> Thanks will do that
>
>
> On Wed, Aug 12, 2015 at 7:58 AM, platzhersh <notifications@github.com>
> wrote:
>
>> @ngagecompany
>> <http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg2B89V8W2zqjvv4WYsTFVQBb2Y56dHtmf7qQxPR02?t=https%3A%2F%2Fgithub.com%2Fngagecompany&si=6216724911226880&pi=d58c6752-25c3-4414-b11d-f0d2a67067e3>
>> This definitely has something to do with your webserver settings. Check if
>> your webhoster allows direct access to .json files.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg2B89V8W2zqjvv4WYsTFVQBb2Y56dHtmf7qQxPR02?t=https%3A%2F%2Fgithub.com%2Fplatzhersh%2Fpacman-canvas%2Fissues%2F4%23issuecomment-130272423&si=6216724911226880&pi=d58c6752-25c3-4414-b11d-f0d2a67067e3>
>> .
>>
>
>
>
> --
> Gregory Panos
> CEO/Founder
> The nGage Company, Inc.
> <http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg2B89V8W2zqjvv4WYsTFVQBb2Y56dHtmf7qQxPR02?t=http%3A%2F%2Fngagecompany.com%2F&si=6216724911226880&pi=14215f6b-a731-4050-987f-389085df10e2>
> greg@ngagecompany.com <gp@thengagecompany.com>
> 484.685.0565 Office
> 484.354.6615 Cell
>
>
>
>


-- 
Gregory Panos
CEO/Founder
The nGage Company, Inc.
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg2B89V8W2zqjvv4WYsTFVQBb2Y56dHtmf7qQxPR02?t=http%3A%2F%2Fngagecompany.com%2F&si=6216724911226880&pi=d58c6752-25c3-4414-b11d-f0d2a67067e3>
greg@ngagecompany.com <gp@thengagecompany.com>
484.685.0565 Office
484.354.6615 Cell
