### ISSUE TITLE
README license differs from LICENSE file

### ISSUE THREAD

**Issue by GoudronViande24** [platzhersh/pacman-canvas#42]
In the Readme, it's written that the project is licensed with Creative Commons Attribution-ShareAlike 4.0 International License.
(By the way, this license is not recommended for this type of projects. CC licenses (except CC0) are not made for programs.)

In the License file, the license is Creative Commons Zero v1.0 Universal.

I would recommend changing the license in the Readme to be also CC0 to avoid confusion and having a license made for programs.

I can also submit a pull request to make the changes recommended here.

**Comment by platzhersh** [comment]
Hey there, 

I'm for sure not a specialist on licenses. So more than happy for suggestions. Feel free to create a pull request.

**Comment by GoudronViande24** [comment]
I opened the pull request with these changes.
See #43

**Comment by GoudronViande24** [comment]
Hi, any update on this?

**Comment by platzhersh** [comment]
Hi @GoudronViande24 thanks for the PR! Didn't get to look at it yet. Will try to do so this or next week.

**Comment by GoudronViande24** [comment]
Hi @platzhersh 

Have you took a look to the PR?

**Comment by cxong** [comment]
The license in package.json should also be changed to match
https://github.com/platzhersh/pacman-canvas/blob/master/package.json#L16

**Comment by platzhersh** [comment]
Thanks for your inputs!
