### ISSUE TITLE
Ghosts

### ISSUE THREAD

**Issue by Rohit-Solanki-6105** [platzhersh/pacman-canvas#59]
- Some Ghosts are not walking and coming out of center
- almost every ghost keeps walking forward even if they can be killed because of big dot they turn blue, they still not trying to go back for a while
- Ghosts speed should be more than pac-man while blue, while not blue speed should a little bit lesser than pac-man

**Comment by platzhersh** [comment]
- the ghosts start coming out more and more every level
- the ghosts change their movement strategy when turning blue

Feel free to fork the code base and create your own version 🤙
