### ISSUE TITLE
Use requestAnimationFrame to be smoother

### ISSUE THREAD

**Issue by gamealchemist** [platzhersh/pacman-canvas#9]
Hello, nice game ! thx for sharing !

  To get a smoother animation, you should use requestAnimationFrame and
have the move time driven. If you want i can do a P.R. with such changes.
Btw i posted about requestAnimationFrame here if you fancy a read :
 http://codepen.io/gamealchemist/post/animationcanvas1

Regards.

**Comment by platzhersh** [comment]
As I am quite occupied with other things at the moment I would suggest that
you just go for it, i will be more than happy to review and merge your PR
:-)

Much appreciated. I will have a look on your article as soon as time allows
me to.

cheers from frosty Switzerland

Chris
Am 18.01.2016 10:36 schrieb "gamealchemist" <notifications@github.com>:
